using System;
using System.Text;

namespace PointlessWaymarksCmsData.Rss
{
    public static class RssStringBuilder
    {
        public static string RssFileString(string channelTitle, string items)
        {
            var rssBuilder = new StringBuilder();
            var settings = UserSettingsSingleton.CurrentSettings();

            rssBuilder.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            rssBuilder.AppendLine("<!--");
            rssBuilder.AppendLine($"    RSS generated by Pointless Waymarks CMS on {DateTime.Now:R}");
            rssBuilder.AppendLine("-->");
            rssBuilder.AppendLine("<rss version=\"2.0\">");
            rssBuilder.AppendLine("<channel>");
            rssBuilder.AppendLine($"<title>{channelTitle}</title>");
            rssBuilder.AppendLine($"<link>https://{settings.SiteUrl}</link>");
            rssBuilder.AppendLine($"<description>{settings.SiteSummary}</description>");
            rssBuilder.AppendLine("<language>en-us</language>");
            rssBuilder.AppendLine($"<copyright>{DateTime.Now.Year} {settings.SiteAuthors}</copyright>");
            rssBuilder.AppendLine($"<lastBuildDate>{DateTime.Now:R}</lastBuildDate>");
            rssBuilder.AppendLine("<generator>Pointless Waymarks CMS</generator>");
            rssBuilder.AppendLine($"<managingEditor>{settings.SiteEmailTo}</managingEditor>");
            rssBuilder.AppendLine($"<webMaster>{settings.SiteEmailTo}</webMaster>");
            rssBuilder.AppendLine(items);
            rssBuilder.AppendLine("</channel>");
            rssBuilder.AppendLine("</rss>");

            return rssBuilder.ToString();
        }

        public static string RssItemString(string title, string link, string content, DateTime createdOn,
            string contentId)
        {
            var rssBuilder = new StringBuilder();

            rssBuilder.AppendLine("    <item>");
            rssBuilder.AppendLine($"        <title>{title}</title>");
            rssBuilder.AppendLine($"        <link>{link}</link>");
            rssBuilder.AppendLine($"        <description><![CDATA[{content}]]></description>");
            rssBuilder.AppendLine($"        <pubDate>{createdOn:R}</pubDate>");
            rssBuilder.AppendLine($"        <guid isPermaLink=\"false\">{contentId}</guid>");
            rssBuilder.AppendLine("    </item>");

            return rssBuilder.ToString();
        }
    }
}