//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointlessWaymarks.SiteViewerGui {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class SiteViewerGuiAppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SiteViewerGuiAppSettings defaultInstance = ((SiteViewerGuiAppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SiteViewerGuiAppSettings())));
        
        public static SiteViewerGuiAppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M:\\PointlessWaymarksPublications")]
        public string ProgramUpdateLocation {
            get {
                return ((string)(this["ProgramUpdateLocation"]));
            }
            set {
                this["ProgramUpdateLocation"] = value;
            }
        }
    }
}
